repos:
  - repo: https://github.com/PyCQA/isort
    rev: "5.13.2"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: "23.12.1"
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: mypy
        language: python
        name: mypy
        entry: mypy
        args: [".", "--config-file", "mypy.ini"]
        pass_filenames: false
        types:
          - "python"
      - id: run-tests
        name: Run Tests
        entry: pytest
        language: python
        types: [python]
